api_keys = ['AIzaSyDZwaX7U_eOb2wGHI_YuPsQkMt8SOP4GFg','AIzaSyDGtfCR1IIy9Gr9vWmzTgIu9-ekge5dI9I',"AIzaSyDonSgPw9gzgetEVk86-UvV4yvdVUvoN5c",'AIzaSyAia-dO5cfunYXGOBAldx88PSV6bIqO70o']

channel_categories = ['Science & Technology']
countries = ['LK', 'IN', 'US', 'UK']


keywords = SEARCH_QUERIES = [
    "algorithm",
    "cybernetics",
    "neuralnet",
    "blockchain",
    "quantum",
    "nanotechnology",
    "cryptography",
    "biotechnology",
    "machinelearning",
    "automation",
    "deepfakes",
    "smartcity",
    "metaverse",
    "databreach",
    "fintech",
    "internetofthings",
    "5G",
    "augmentedreality",
    "cloudstorage",
    "edgecomputing",
    "datascience",
    "robotics",
    "digitaltwin",
    "bigdata",
    "cryptocurrency",
    "holography",
    "wearables",
    "syntheticlearning",
    "predictiveanalytics",
    "bioinformatics",
    "intelligentautomation",
    "neuralprocessing",
    "facialrecognition",
    "intelligentsystems",
    "cloudcomputing",
    "cybersecurity",
    "opensource",
    "geospatialdata",
    "privacytech",
    "blockchainsecurity",
    "datavisualization",
    "unmannedvehicles",
    "exoskeletons",
    "cloudAI",
    "drones",
    "quantumcomputing",
    "deepneuralnetworks",
    "turingtest",
    "autonomoussystems",
    "AIethics",
    "biorobotics"
]
